sync:
  image: n3llyb0y/wait
  links:
    - plugind
    - swagger-validator
  environment:
    PORTS: "9503 8080"

plugind:
  image: "wazo-plugind-test"
  environment:
    - XIVO_UUID=cd030e68-ace9-4ad4-bc4e-13c8dec67898
  volumes:
    - "../../..:/usr/src/wazo-plugind"
    - "./etc/wazo-plugind/conf.d/disable_service_discovery.yml:/etc/wazo-plugind/conf.d/disable_service_discovery.yml"
  ports:
    - "9503"

swagger-validator:
  image: swaggerapi/swagger-validator
  ports:
    - "18080:8080"
  links:
    - plugind
