# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: '/etc/wazo-plugind/conf.d'

debug: false
foreground: false
log_level: info
log_file: /var/log/wazo-plugind.log
pid_file: /var/run/wazo-plugind/wazo-plugind.pid
rest_api:
  https:
    listen: 0.0.0.0
